### ISSUE TITLE
Uncaught SyntaxError: Unexpected token j in JSON at position 0

### ISSUE THREAD

**Issue by tschf** [bmazzarol/atom-plsql-linter#1]
I seem to get an error the first time I save an SQL file, After that initial error popping up both in Atom and on the command line, everything (linting wise) seems to work as expected.

Reproduce steps

1. Start the server
2. Go into Atom and save a file with the extension sql
3. See the below errors pop up

The HTTP server error output:

```
[ERROR] [05/27/2017 08:24:22.504] [default-server-dispatcher-8] [/plsql-lint-server(akka://default)] Error processing request: HttpRequest(ParsedHead(Post /lint-file/%2Fhome%2Ftrent%2FProjects%2Fig-notes%2Ftest2.sql 1.1,[content-type:application/JSON content-length:164 host:localhost:9999 connection:close]),create or replace function foo  return varchar2 deterministic
as

    subtype String is varchar2(200);
    l_const constant String := 'TEST';
begin


    
end foo;
): java.lang.NullPointerException
java.lang.NullPointerException
	at scala.Predef$.Integer2int(Predef.scala:362)
	at bmazzarol.plsql.AST$.range(AST.scala:34)
	at bmazzarol.plsql.AST$.message(AST.scala:60)
	at bmazzarol.plsql.PLSQLLintServer$$anonfun$bmazzarol$plsql$PLSQLLintServer$$lintFile$1$1.apply(PLSQLLintServer.scala:63)
	at bmazzarol.plsql.PLSQLLintServer$$anonfun$bmazzarol$plsql$PLSQLLintServer$$lintFile$1$1.apply(PLSQLLintServer.scala:63)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:241)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
	at bmazzarol.plsql.PLSQLLintServer$.bmazzarol$plsql$PLSQLLintServer$$lintFile$1(PLSQLLintServer.scala:63)
	at bmazzarol.plsql.PLSQLLintServer$$anonfun$main$1$$anon$1$$anonfun$handle$1.applyOrElse(PLSQLLintServer.scala:73)
	at bmazzarol.plsql.PLSQLLintServer$$anonfun$main$1$$anon$1$$anonfun$handle$1.applyOrElse(PLSQLLintServer.scala:69)
	at scala.PartialFunction$OrElse.apply(PartialFunction.scala:167)
	at colossus.service.Service.processRequest(ServiceDSL.scala:106)
	at colossus.protocols.http.package$BaseHttpServiceHandler.processRequest(package.scala:74)
	at colossus.protocols.http.package$BaseHttpServiceHandler.processRequest(package.scala:68)
	at colossus.service.ServiceServer.processMessage(ServiceServer.scala:262)
	at colossus.controller.InputController$class.receivedData(InputController.scala:143)
	at colossus.controller.Controller.receivedData(Controller.scala:67)
	at colossus.core.Connection.handleRead(Connection.scala:193)
	at colossus.core.Worker.selectLoop(Worker.scala:490)
	at colossus.core.Worker$$anonfun$accepting$1.applyOrElse(Worker.scala:197)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:465)
	at colossus.core.Worker.aroundReceive(Worker.scala:147)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:254)
	at akka.dispatch.Mailbox.run(Mailbox.scala:221)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
```

And my Atom environment/error output:

**Atom**: 1.17.2 x64
**Electron**: 1.3.15
**OS**: Ubuntu 16.04.2
**Thrown From**: [plsql-linter](https://github.com/bmazzarol/atom-plsql-linter) package 2.1.0

### Stack Trace

Uncaught SyntaxError: Unexpected token j in JSON at position 0

```
At file:///home/trent/.local/share/umake/ide/atom/resources/app/static/index.html:1

SyntaxError: Unexpected token j in JSON at position 0
    at Object.parse (native)
    at /packages/plsql-linter/lib/index.js:108:47)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
     -1:03.0 core:save (input.hidden-input)
     -0:59 intentions:highlight (input.hidden-input)
     -0:58.9.0 core:save (input.hidden-input)
     -0:54.1.0 snippets:next-tab-stop (input.hidden-input)
     -0:54.1.0 snippets:expand (input.hidden-input)
     -0:54.1.0 editor:indent (input.hidden-input)
     -0:52.8.0 intentions:highlight (input.hidden-input)
     -0:52.7.0 core:save (input.hidden-input)
  5x -0:48.5.0 core:backspace (input.hidden-input)
     -0:47.6.0 intentions:highlight (input.hidden-input)
     -0:47.6.0 core:save (input.hidden-input)
     -0:18.8.0 intentions:highlight (input.hidden-input)
     -0:18.7.0 core:save (input.hidden-input)
     -0:17.4.0 editor:newline (input.hidden-input)
     -0:16.3.0 intentions:highlight (input.hidden-input)
     -0:16.1.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atomic-chrome 0.3.0 
autocomplete-oracle 0.4.0 
build 0.68.0 
build-oracle 1.6.0 
busy 0.7.0 
busy-signal 1.4.1 
color-picker 2.2.5 
data-atom 0.25.1 
file-icons 2.1.6 
file-type-icons 1.3.4 
git-plus 7.8.0 
go-debug 1.3.2 
go-plus 5.5.5 
go-signature-statusbar 1.2.0 
hyperclick 0.0.40 
intentions 1.1.2 
language-ada 1.1.0 
language-oracle 1.8.0 
linter 2.1.4 
linter-ui-default 1.2.4 
node-debug undefined 
pigments 0.39.1 
platformio-ide-terminal 2.5.1 
plsql-block 0.0.1 
plsql-linter 2.1.0 
prettier-atom 0.31.1 
project-manager 3.3.4 
remote-edit 1.9.0 
script 3.15.0 
symbols-tree-view 0.14.0 
```

**Comment by bmazzarol** [comment]
@tschf thanks for having a play with the linter. The error looks like it is on the server side. I will raise a bug on that repo and when I have resolved it I will close this one and do a release.

**Comment by tschf** [comment]
> @tschf thanks for having a play with the linter

No problem - I just happened to stumble on this yesterday when I was installing packages on a new system. From my quick test, it's seems like it will be a very welcome addition to Oracle development!
